version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      # check out our code
      - checkout

      - run:
          name: Deploy to staging
          command: pwd

notify:
  webhooks:
    - url: https://api.ghostinspector.com/v1/suites/5ad4fd966cca1a35967abcd1/execute/?apiKey=af923ddcd57dcaca093c7369f3768abf631bb379&startUrl=my-staging.site.comL&immediate=1