version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      # required to run multiple containers
      - setup_remote_docker
      # check out our code
      - checkout

      - run:
          name: Build my application
          # build our app and call it 
          command: |
            docker build -t my-app:0.1.$CIRCLE_BUILD_NUM .

      - run:
          name: Execute test
          command: |
            docker network create temp-network
            docker run -d \
              --network temp-network \
              --name my-app \
              my-app:0.1.$CIRCLE_BUILD_NUM --sha=$CIRCLE_SHA1

            docker run \
              -e APP_PORT=my-app:$APP_PORT \
              -e GI_API_KEY=$GI_API_KEY \
              -e GI_SUITE=$GI_SUITE \
              -e NGROK_TOKEN=$NGROK_TOKEN \
              --network temp-network \
              ghostinspector/my-runner-standalone
            
